#!/usr/bin/env python3
"""Regenerate the command line reference nav section in mkdocs.yml.

The pages in src/command-line-reference are generated by `apppack docgen`
and not committed, so their nav entries are regenerated alongside them
(see the cli-docs target in the Makefile). Page titles are taken from
each page's H1 at build time, so only the paths are listed here.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
CONFIG = ROOT / "mkdocs.yml"
CLI_DOCS = ROOT / "src" / "command-line-reference"
BEGIN = "# BEGIN cli-nav (generated)"
END = "# END cli-nav (generated)"


def main() -> int:
    pages = sorted(p.name for p in CLI_DOCS.glob("*.md"))
    if not pages:
        print(f"No pages found in {CLI_DOCS}. Run `apppack docgen` first.", file=sys.stderr)
        return 1

    lines = CONFIG.read_text().splitlines()
    try:
        begin = next(i for i, l in enumerate(lines) if l.strip() == BEGIN)
        end = next(i for i, l in enumerate(lines) if l.strip() == END)
    except StopIteration:
        print(f"cli-nav markers not found in {CONFIG}", file=sys.stderr)
        return 1

    indent = " " * (len(lines[begin]) - len(lines[begin].lstrip()))
    entries = [f"{indent}- command-line-reference/{name}" for name in pages]
    lines[begin + 1 : end] = entries
    CONFIG.write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(pages)} command line reference nav entries to {CONFIG}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
