---
name: build

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version-file: "pyproject.toml"

      - uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Tests
        run: uv run --frozen pytest

      - name: AppPack CLI
        uses: apppackio/setup-apppack-cli@142a1bbcffd0e1fde615b64efd6bd63a3eab7198 # v1.2.0

      - name: CLI docs
        run: make cli-docs
      - name: Check nav is complete
        run: make check-nav
      - name: Build
        run: APPPACK_VERSION=$(apppack version) make build
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          path: public
          retention-days: 3
  deploy:
    needs: [build]
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/deploy/prod'
    environment: production
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ROLE_ARN: "arn:aws:iam::101287669015:role/docs-github-actions"
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: artifact
          path: artifact
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Deploy
        run: mv artifact public && make deploy
